site_name: aimsprop
theme:
  name: material
  palette:
    - scheme: default
      primary: pink
      accent: cyan
  features:
    - search.suggest
    - search.highlight
    - navigation.instant
    - navigation.expand
  icon:
    repo: fontawesome/brands/github-alt

repo_url: https://github.com/mtzgroup/aimsprop
edit_uri: edit/develop/docs/
site_author: Colton Hicks
extra_css:
  - css/extra.css
plugins:
  - mkdocstrings:
      watch:
        - aimsprop
        - scripts
      handlers:
        python:
          rendering:
            show_root_heading: True
            show_root_full_path: True
            show_category_heading: True
            show_signature_annotations: True
            show_if_no_docstring: True
            group_by_category: True
            heading_level: 2
          selection:
            new_path_syntax: True
            inherited_members: True
            filters:
              - "!^_"
              - "^__init__$"
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - admonition
  - toc:
      permalink: 🔗
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
