name: Python package

on: [push]

jobs:
  flake8_selected_files_only:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.6"
      - name: Install flake8
        run: pip install flake8
      - name: Flake8 TESTS ONLY RIGHT NOW (because library is such a mess)
        run: flake8 tests aimsprop/fms90.py scripts

  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.6"
      - name: Install black
        run: pip install black
      - name: Check code formatting with black
        run: black --check .

  isort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.6"
      - name: upgrade pip
        run: pip install --upgrade pip
      - name: Install flit
        run: pip install flit
      - name: Install aimsprop
        run: flit install --deps develop --symlink
      - name: Check import formatting with isort
        run: isort --check-only --diff aimsprop examples tests scripts

  markdown_checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run mdl (markdown linter)
        uses: actionshub/markdownlint@main
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.6"
      - name: Install flit
        run: pip install flit
      - name: Install aimsprop
        run: flit install --deps develop --symlink
      - name: Build Documentation
        run: mkdocs build

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.6"
      - name: upgrade pip
        run: pip install --upgrade pip
      - name: Install flit
        run: pip install flit
      - name: Install aimsprop
        run: flit install --deps develop --symlink
      - name: Test with pytest
        run: pytest
      - name: Upload pytest test results
        uses: actions/upload-artifact@v2
        with:
          name: htmlcov
          path: htmlcov/*
        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}
